/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PocRouteImport } from './routes/poc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiKrokiRenderRouteImport } from './routes/api/kroki/render'

const PocRoute = PocRouteImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKrokiRenderRoute = ApiKrokiRenderRouteImport.update({
  id: '/api/kroki/render',
  path: '/api/kroki/render',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poc': typeof PocRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/kroki/render': typeof ApiKrokiRenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poc': typeof PocRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/kroki/render': typeof ApiKrokiRenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poc': typeof PocRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/kroki/render': typeof ApiKrokiRenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/poc' | '/api/files' | '/api/health' | '/api/kroki/render'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/poc' | '/api/files' | '/api/health' | '/api/kroki/render'
  id:
    | '__root__'
    | '/'
    | '/poc'
    | '/api/files'
    | '/api/health'
    | '/api/kroki/render'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PocRoute: typeof PocRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiKrokiRenderRoute: typeof ApiKrokiRenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/poc': {
      id: '/poc'
      path: '/poc'
      fullPath: '/poc'
      preLoaderRoute: typeof PocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kroki/render': {
      id: '/api/kroki/render'
      path: '/api/kroki/render'
      fullPath: '/api/kroki/render'
      preLoaderRoute: typeof ApiKrokiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PocRoute: PocRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiKrokiRenderRoute: ApiKrokiRenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
