/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PocRouteImport } from './routes/poc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiKrokiRenderRouteImport } from './routes/api/kroki/render'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiPingRouteImport } from './routes/api/ai/ping'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PocRoute = PocRouteImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKrokiRenderRoute = ApiKrokiRenderRouteImport.update({
  id: '/api/kroki/render',
  path: '/api/kroki/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPingRoute = ApiAiPingRouteImport.update({
  id: '/api/ai/ping',
  path: '/api/ai/ping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/poc': typeof PocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/ping': typeof ApiAiPingRoute
  '/api/kroki/render': typeof ApiKrokiRenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/poc': typeof PocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/ping': typeof ApiAiPingRoute
  '/api/kroki/render': typeof ApiKrokiRenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/poc': typeof PocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/ping': typeof ApiAiPingRoute
  '/api/kroki/render': typeof ApiKrokiRenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/poc' | '/api/health' | '/api/ai/chat' | '/api/ai/ping' | '/api/kroki/render'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/poc' | '/api/health' | '/api/ai/chat' | '/api/ai/ping' | '/api/kroki/render'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/poc'
    | '/api/health'
    | '/api/ai/chat'
    | '/api/ai/ping'
    | '/api/kroki/render'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  PocRoute: typeof PocRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiPingRoute: typeof ApiAiPingRoute
  ApiKrokiRenderRoute: typeof ApiKrokiRenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc': {
      id: '/poc'
      path: '/poc'
      fullPath: '/poc'
      preLoaderRoute: typeof PocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kroki/render': {
      id: '/api/kroki/render'
      path: '/api/kroki/render'
      fullPath: '/api/kroki/render'
      preLoaderRoute: typeof ApiKrokiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/ping': {
      id: '/api/ai/ping'
      path: '/api/ai/ping'
      fullPath: '/api/ai/ping'
      preLoaderRoute: typeof ApiAiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  PocRoute: PocRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiPingRoute: ApiAiPingRoute,
  ApiKrokiRenderRoute: ApiKrokiRenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
